// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    HELLO_GUEST_ELF, HELLO_GUEST_ID
};
use risc0_zkvm::{default_prover, ExecutorEnv};

// use methods::{HELLO_GUEST_ELF, HELLO_GUEST_ID};
// use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {
    let input: u32 = 7;
    let env = ExecutorEnv::builder().write(&input).unwrap().build().unwrap();
}
