// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/carbonemission.proto

package zeebe_go_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmissionProofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consumption    uint32 `protobuf:"varint,1,opt,name=consumption,proto3" json:"consumption,omitempty"`
	EmissionFactor uint32 `protobuf:"varint,2,opt,name=emission_factor,json=emissionFactor,proto3" json:"emission_factor,omitempty"`
}

func (x *EmissionProofRequest) Reset() {
	*x = EmissionProofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_carbonemission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmissionProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmissionProofRequest) ProtoMessage() {}

func (x *EmissionProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbonemission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmissionProofRequest.ProtoReflect.Descriptor instead.
func (*EmissionProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_carbonemission_proto_rawDescGZIP(), []int{0}
}

func (x *EmissionProofRequest) GetConsumption() uint32 {
	if x != nil {
		return x.Consumption
	}
	return 0
}

func (x *EmissionProofRequest) GetEmissionFactor() uint32 {
	if x != nil {
		return x.EmissionFactor
	}
	return 0
}

type EmissionProofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Co2Emissions string `protobuf:"bytes,1,opt,name=co2_emissions,json=co2Emissions,proto3" json:"co2_emissions,omitempty"`
}

func (x *EmissionProofResponse) Reset() {
	*x = EmissionProofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_carbonemission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmissionProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmissionProofResponse) ProtoMessage() {}

func (x *EmissionProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_carbonemission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmissionProofResponse.ProtoReflect.Descriptor instead.
func (*EmissionProofResponse) Descriptor() ([]byte, []int) {
	return file_proto_carbonemission_proto_rawDescGZIP(), []int{1}
}

func (x *EmissionProofResponse) GetCo2Emissions() string {
	if x != nil {
		return x.Co2Emissions
	}
	return ""
}

var File_proto_carbonemission_proto protoreflect.FileDescriptor

var file_proto_carbonemission_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x65, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x61,
	0x72, 0x62, 0x6f, 0x6e, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x14,
	0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0e, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22,
	0x3c, 0x0a, 0x15, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x32, 0x5f,
	0x65, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x6f, 0x32, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x76, 0x0a,
	0x0e, 0x43, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x64, 0x0a, 0x15, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x5f,
	0x65, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x72, 0x62, 0x6f,
	0x6e, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x6e, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x45, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x73, 0x6d, 0x61, 0x75, 0x67, 0x2f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x2f, 0x7a, 0x65, 0x65, 0x62, 0x65, 0x2d, 0x67, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_carbonemission_proto_rawDescOnce sync.Once
	file_proto_carbonemission_proto_rawDescData = file_proto_carbonemission_proto_rawDesc
)

func file_proto_carbonemission_proto_rawDescGZIP() []byte {
	file_proto_carbonemission_proto_rawDescOnce.Do(func() {
		file_proto_carbonemission_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_carbonemission_proto_rawDescData)
	})
	return file_proto_carbonemission_proto_rawDescData
}

var file_proto_carbonemission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_carbonemission_proto_goTypes = []any{
	(*EmissionProofRequest)(nil),  // 0: carbonemission.EmissionProofRequest
	(*EmissionProofResponse)(nil), // 1: carbonemission.EmissionProofResponse
}
var file_proto_carbonemission_proto_depIdxs = []int32{
	0, // 0: carbonemission.CarbonEmission.prove_carbon_emission:input_type -> carbonemission.EmissionProofRequest
	1, // 1: carbonemission.CarbonEmission.prove_carbon_emission:output_type -> carbonemission.EmissionProofResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_carbonemission_proto_init() }
func file_proto_carbonemission_proto_init() {
	if File_proto_carbonemission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_carbonemission_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmissionProofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_carbonemission_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EmissionProofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_carbonemission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_carbonemission_proto_goTypes,
		DependencyIndexes: file_proto_carbonemission_proto_depIdxs,
		MessageInfos:      file_proto_carbonemission_proto_msgTypes,
	}.Build()
	File_proto_carbonemission_proto = out.File
	file_proto_carbonemission_proto_rawDesc = nil
	file_proto_carbonemission_proto_goTypes = nil
	file_proto_carbonemission_proto_depIdxs = nil
}
