apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-core.yaml -o kubernetes-maifests/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-core.yaml -o kubernetes-maifests/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "false"
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          image: 'docker.elastic.co/elasticsearch/elasticsearch:'
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:9200/_cat/health | grep -q green
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 5
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic
      restartPolicy: Always
      volumes:
        - name: elastic
          persistentVolumeClaim:
            claimName: elastic
