apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-core.yaml -o kubernetes-maifests/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: operate
  name: operate
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: operate
