apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-core.yaml -o helm -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kibana
    spec:
      containers:
        - image: 'docker.elastic.co/kibana/kibana:{{ .Values.elasticsearch.version }}'
          name: kibana
          ports:
            - containerPort: 5601
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/kibana/data
              name: kibana
      restartPolicy: Always
      volumes:
        - name: kibana
          persistentVolumeClaim:
            claimName: kibana
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
  selector:
    io.kompose.service: kibana
