apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-core.yaml -o helm -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: operate
  name: operate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: operate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-core.yaml -o helm -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: operate
    spec:
      containers:
        - env:
            - name: CAMUNDA_OPERATE_ELASTICSEARCH_URL
              value: http://elasticsearch:9200
            - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL
              value: http://elasticsearch:9200
            - name: CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS
              value: zeebe:26500
            - name: management.endpoint.health.probes.enabled
              value: "true"
            - name: management.endpoints.web.exposure.include
              value: health
          image: 'camunda/operate:{{ .Values.camunda.platform.version }}'
          livenessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
          name: operate
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
