apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-core.yaml -o helm -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: zeebe
  name: zeebe
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zeebe
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-core.yaml -o helm -c
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: zeebe
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xms512m -Xmx512m
            - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
              value: "0.998"
            - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
              value: "0.999"
            - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE
              value: "1"
            - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL
              value: http://elasticsearch:9200
            - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
              value: io.camunda.zeebe.exporter.ElasticsearchExporter
          image: 'camunda/zeebe:{{ .Values.camunda.platform.version }}'
          #livenessProbe:
          #  exec:
          #    command:
          #      - timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1
          #  failureThreshold: 5
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
          #  timeoutSeconds: 5
          name: zeebe
          ports:
            - containerPort: 26500
              protocol: TCP
            - containerPort: 9600
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/zeebe/data
              name: zeebe
      restartPolicy: Always
      volumes:
        - name: zeebe
          persistentVolumeClaim:
            claimName: zeebe
