apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-core.yaml -o helm -c
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: zeebe
  name: zeebe
spec:
  ports:
    - name: "26500"
      port: 26500
      targetPort: 26500
    - name: "9600"
      port: 9600
      targetPort: 9600
    - name: "8088"
      port: 8088
      targetPort: 8080
  selector:
    io.kompose.service: zeebe
